# Generated by Django 5.1 on 2024-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
