# Generated by Django 5.1 on 2024-08-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurants_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='adress',
            new_name='address',
        ),
    ]
