# Generated by Django 5.1 on 2024-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_adress_restaurants_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(upload_to='restaurants/'),
        ),
    ]
