# Generated by Django 5.1 on 2024-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurants_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
